<?php

namespace AdminBundle\Repository;

/**
 * MenucantineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenucantineRepository extends \Doctrine\ORM\EntityRepository
{
}
