<?php

namespace AdminBundle\Repository\Esparent;

/**
 * payementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class payementRepository extends \Doctrine\ORM\EntityRepository
{
}
