<?php

namespace AdminBundle\Repository\Esparent;

/**
 * reclamtionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class reclamtionRepository extends \Doctrine\ORM\EntityRepository
{
}
